import LoadJavasript from "@/components/loadJavasript";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container-fluid m-4">
        <LoadJavasript />
        {children}
      </body>
    </html>
  );
}
